name: AUTO-CHECKIN
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
  schedule:
    - cron: 1 4,16 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: install dependencies
        run: pip install httpx bs4

      - name: checkin
        env:
          CHICKEN_MAIL: ${{ secrets.CHICKEN_MAIL }}
          CHICKEN_PASSWORD: ${{ secrets.CHICKEN_PASSWORD }}
          LOVEZHUOYOU_USER: ${{ secrets.LOVEZHUOYOU_USER }}
          LOVEZHUOYOU_PASSWORD: ${{ secrets.LOVEZHUOYOU_PASSWORD }}
          VGTIME_USER: ${{ secrets.VGTIME_USER }}
          VGTIME_PASSWORD: ${{ secrets.VGTIME_PASSWORD }}
          IYINGDI_USER: ${{ secrets.IYINGDI_USER }}
          IYINGDI_PASSWORD: ${{ secrets.IYINGDI_PASSWORD }}
          KKGAL_USER: ${{ secrets.KKGAL_USER }}
          KKGAL_PASSWORD: ${{ secrets.KKGAL_PASSWORD }}
          SUYING_USER: ${{ secrets.SUYING_USER }}
          SUYING_PASSWORD: ${{ secrets.SUYING_PASSWORD }}
          SMZDM_SESS_COOKIE: ${{ secrets.SMZDM_SESS_COOKIE }}
        run: python checkin.py
